version: 2.1

jobs:
  unit_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is the build job"
  integration_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is the build job"
  build_promote_to_docker:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is the build job"
  deploy_to_dev:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is the build job"
  deploy_to_production:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is the build job"

workflows:
  jobs:
    - unit_test
    - integration_test
    - build_promote_to_docker:
        requires:
          - "integration_test"
    - deploy_to_dev:
        requires:
          - "build_promote_to_docker"
    - deploy_to_production:
        type: approval
        requires:
          - "build_promote_to_docker"