version: 2.1

commands:
  save_m2_cache:
    steps:
      - save_cache:
          paths:
            - "~/.m2"
          key: v1-dependencies-{{ checksum "pom.xml" }}

jobs:
  unit_test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - run: java --version
      - checkout
      - save_m2_cache
      - run: echo "this unit_test"
  integration_test:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: echo "this is integration_tes stept"
  build_promote_to_docker:
    working_directory: ~/agent-service
    environment:
      VERSION: 1.0.<< pipeline.number >>
      SERVICE_NAME: "agent-service"
      IMAGE_NAME: "ojoadeolagabriel/agent-service"
      RESOLVED_NAME: "${IMAGE_NAME}:${VERSION}"
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: ls -al && echo "this is build_promote_to_docker step with revision << pipeline.git.revision >>"
      - run: "_promote/build_promote.sh"
  deploy_to_dev:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is deploy_to_dev"
  deploy_to_production:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "this is deploy_to_production"

workflows:
  test_and_build:
    jobs:
      - unit_test
      - integration_test
  build:
    jobs:
      - build_promote_to_docker:
          name: "build_promote_to_docker"
  deploy:
    jobs:
      - deploy_to_dev:
          name: "deploy_to_dev"
      - deploy_to_production:
          type: approval
          name: "deploy_to_production"