---
apiVersion: v1
kind: Namespace
metadata:
  name: location-ns
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: listing-service-config-map
  namespace: location-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: location-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
        - name: listing-service
          image: ojoadeolagabriel/listing-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 12345
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 12345
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: listing-service-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
  namespace: location-ns
spec:
  selector:
    app: listing-service-service
  ports:
    - port: 50000
      targetPort: 12345
  type: LoadBalancer